buildscript {
    repositories {

        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://jitpack.io' } // GreenDAO托管地址

        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }

        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.3.1'

    }
}


plugins{
    id 'com.android.application' version '8.8.0' apply false
    id 'com.android.library' version '8.8.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.20' apply false
}