package com.baoge.wnotes.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.baoge.wnotes.db.City;
import com.baoge.wnotes.db.Department;
import com.baoge.wnotes.db.Device;
import com.baoge.wnotes.db.Hospital;
import com.baoge.wnotes.db.Installer;
import com.baoge.wnotes.db.Order;
import com.baoge.wnotes.db.Technician;

import com.baoge.wnotes.dao.CityDao;
import com.baoge.wnotes.dao.DepartmentDao;
import com.baoge.wnotes.dao.DeviceDao;
import com.baoge.wnotes.dao.HospitalDao;
import com.baoge.wnotes.dao.InstallerDao;
import com.baoge.wnotes.dao.OrderDao;
import com.baoge.wnotes.dao.TechnicianDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig departmentDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig hospitalDaoConfig;
    private final DaoConfig installerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig technicianDaoConfig;

    private final CityDao cityDao;
    private final DepartmentDao departmentDao;
    private final DeviceDao deviceDao;
    private final HospitalDao hospitalDao;
    private final InstallerDao installerDao;
    private final OrderDao orderDao;
    private final TechnicianDao technicianDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        departmentDaoConfig = daoConfigMap.get(DepartmentDao.class).clone();
        departmentDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        hospitalDaoConfig = daoConfigMap.get(HospitalDao.class).clone();
        hospitalDaoConfig.initIdentityScope(type);

        installerDaoConfig = daoConfigMap.get(InstallerDao.class).clone();
        installerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        technicianDaoConfig = daoConfigMap.get(TechnicianDao.class).clone();
        technicianDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        departmentDao = new DepartmentDao(departmentDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        hospitalDao = new HospitalDao(hospitalDaoConfig, this);
        installerDao = new InstallerDao(installerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        technicianDao = new TechnicianDao(technicianDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(Department.class, departmentDao);
        registerDao(Device.class, deviceDao);
        registerDao(Hospital.class, hospitalDao);
        registerDao(Installer.class, installerDao);
        registerDao(Order.class, orderDao);
        registerDao(Technician.class, technicianDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        departmentDaoConfig.clearIdentityScope();
        deviceDaoConfig.clearIdentityScope();
        hospitalDaoConfig.clearIdentityScope();
        installerDaoConfig.clearIdentityScope();
        orderDaoConfig.clearIdentityScope();
        technicianDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public DepartmentDao getDepartmentDao() {
        return departmentDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public HospitalDao getHospitalDao() {
        return hospitalDao;
    }

    public InstallerDao getInstallerDao() {
        return installerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public TechnicianDao getTechnicianDao() {
        return technicianDao;
    }

}
